require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestionResponsesController do
  before(:all) do
    @question_response = Factory(:question_response)
    
    # This should return the minimal set of attributes required to create a valid
    # QuestionResponse. As you add validations to QuestionResponse, be sure to
    # update the return value of this method accordingly.
    @valid_attributes = {
      :question_id => @question_response.question_id,
      :user_id => @question_response.user_id,
      :response => @question_response.response
    }
  end

  describe "GET index" do
    it "assigns all question_responses as @question_responses" do
      get :index
      assigns(:question_responses).should eq(QuestionResponse.all)
    end
  end

  describe "GET show" do
    it "assigns the requested question_response as @question_response" do
      get :show, :id => @question_response.id
      assigns(:question_response).should eq(@question_response)
    end
  end

  describe "GET new" do
    it "assigns a new question_response as @question_response" do
      get :new
      assigns(:question_response).should be_a_new(QuestionResponse)
    end
  end

  describe "GET edit" do
    it "assigns the requested question_response as @question_response" do
      get :edit, :id => @question_response.id
      assigns(:question_response).should eq(@question_response)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuestionResponse" do
        expect {
          post :create, :question_response => @valid_attributes
        }.to change(QuestionResponse, :count).by(1)
      end

      it "assigns a newly created question_response as @question_response" do
        post :create, :question_response => @valid_attributes
        assigns(:question_response).should be_a(QuestionResponse)
        assigns(:question_response).should be_persisted
      end

      it "redirects to the created question_response" do
        post :create, :question_response => @valid_attributes
        response.should redirect_to(QuestionResponse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved question_response as @question_response" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionResponse.any_instance.stub(:save).and_return(false)
        post :create, :question_response => {}
        assigns(:question_response).should be_a_new(QuestionResponse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionResponse.any_instance.stub(:save).and_return(false)
        post :create, :question_response => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested question_response" do
        # Assuming there are no other question_responses in the database, this
        # specifies that the QuestionResponse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuestionResponse.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => @question_response.id, :question_response => {'these' => 'params'}
      end

      it "assigns the requested question_response as @question_response" do
        put :update, :id => @question_response.id, :question_response => @valid_attributes
        assigns(:question_response).should eq(@question_response)
      end

      it "redirects to the question_response" do
        put :update, :id => @question_response.id, :question_response => @valid_attributes
        response.should redirect_to(@question_response)
      end
    end

    describe "with invalid params" do
      it "assigns the question_response as @question_response" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionResponse.any_instance.stub(:save).and_return(false)
        put :update, :id => @question_response.id, :question_response => {}
        assigns(:question_response).should eq(@question_response)
      end

      it "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionResponse.any_instance.stub(:save).and_return(false)
        put :update, :id => @question_response.id, :question_response => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested question_response" do
      question_response = QuestionResponse.create! @valid_attributes
      expect {
        delete :destroy, :id => question_response.id
      }.to change(QuestionResponse, :count).by(-1)
    end

    it "redirects to the question_responses list" do
      question_response = QuestionResponse.create! @valid_attributes
      delete :destroy, :id => question_response.id
      response.should redirect_to(question_responses_url)
    end
  end

end
