require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RadialsController do
  before(:all) do
    @radial = Factory(:radial)
    
    # This should return the minimal set of attributes required to create a valid
    # Radial. As you add validations to Radial, be sure to
    # update the return value of this method accordingly.
    @valid_attributes = {
      :name => @radial.name,
      :project_id => @radial.project_id
    }
  end

  describe "GET index" do
    it "assigns all radials as @radials" do
      get :index
      assigns(:radials).should eq(Radial.all)
    end
  end

  describe "GET show" do
    it "assigns the requested radial as @radial" do
      get :show, :id => @radial.id
      assigns(:radial).should eq(@radial)
    end
  end

  describe "GET new" do
    it "assigns a new radial as @radial" do
      get :new
      assigns(:radial).should be_a_new(Radial)
    end
  end

  describe "GET edit" do
    it "assigns the requested radial as @radial" do
      get :edit, :id => @radial.id
      assigns(:radial).should eq(@radial)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Radial" do
        expect {
          post :create, :radial => @valid_attributes
        }.to change(Radial, :count).by(1)
      end

      it "assigns a newly created radial as @radial" do
        post :create, :radial => @valid_attributes
        assigns(:radial).should be_a(Radial)
        assigns(:radial).should be_persisted
      end

      it "redirects to the created radial" do
        post :create, :radial => @valid_attributes
        response.should redirect_to(Radial.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved radial as @radial" do
        # Trigger the behavior that occurs when invalid params are submitted
        Radial.any_instance.stub(:save).and_return(false)
        post :create, :radial => {}
        assigns(:radial).should be_a_new(Radial)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Radial.any_instance.stub(:save).and_return(false)
        post :create, :radial => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested radial" do
        # Assuming there are no other radials in the database, this
        # specifies that the Radial created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Radial.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => @radial.id, :radial => {'these' => 'params'}
      end

      it "assigns the requested radial as @radial" do
        put :update, :id => @radial.id, :radial => @valid_attributes
        assigns(:radial).should eq(@radial)
      end

      it "redirects to the radial" do
        put :update, :id => @radial.id, :radial => @valid_attributes
        response.should redirect_to(@radial)
      end
    end

    describe "with invalid params" do
      it "assigns the radial as @radial" do
        # Trigger the behavior that occurs when invalid params are submitted
        Radial.any_instance.stub(:save).and_return(false)
        put :update, :id => @radial.id, :radial => {}
        assigns(:radial).should eq(@radial)
      end

      it "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Radial.any_instance.stub(:save).and_return(false)
        put :update, :id => @radial.id, :radial => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested radial" do
      radial = Radial.create! @valid_attributes
      expect {
        delete :destroy, :id => radial.id
      }.to change(Radial, :count).by(-1)
    end

    it "redirects to the radials list" do
      radial = Radial.create! @valid_attributes
      delete :destroy, :id => radial.id
      response.should redirect_to(radials_url)
    end
  end

end
