require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SuggestionVotesController do
  before(:all) do
    @suggestion_vote = Factory(:suggestion_vote)
    
    # This should return the minimal set of attributes required to create a valid
    # SuggestionVote. As you add validations to SuggestionVote, be sure to
    # update the return value of this method accordingly.
    @valid_attributes = {
      :suggestion_id => @suggestion_vote.suggestion_id,
      :user_id => @suggestion_vote.user_id,
      :vote => @suggestion_vote.vote
    }
  end

  describe "GET index" do
    it "assigns all suggestion_votes as @suggestion_votes" do
      get :index
      assigns(:suggestion_votes).should eq(SuggestionVote.all)
    end
  end

  describe "GET show" do
    it "assigns the requested suggestion_vote as @suggestion_vote" do
      get :show, :id => @suggestion_vote.id
      assigns(:suggestion_vote).should eq(@suggestion_vote)
    end
  end

  describe "GET new" do
    it "assigns a new suggestion_vote as @suggestion_vote" do
      get :new
      assigns(:suggestion_vote).should be_a_new(SuggestionVote)
    end
  end

  describe "GET edit" do
    it "assigns the requested suggestion_vote as @suggestion_vote" do
      get :edit, :id => @suggestion_vote.id
      assigns(:suggestion_vote).should eq(@suggestion_vote)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SuggestionVote" do
        expect {
          post :create, :suggestion_vote => @valid_attributes
        }.to change(SuggestionVote, :count).by(1)
      end

      it "assigns a newly created suggestion_vote as @suggestion_vote" do
        post :create, :suggestion_vote => @valid_attributes
        assigns(:suggestion_vote).should be_a(SuggestionVote)
        assigns(:suggestion_vote).should be_persisted
      end

      it "redirects to the created suggestion_vote" do
        post :create, :suggestion_vote => @valid_attributes
        response.should redirect_to(SuggestionVote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved suggestion_vote as @suggestion_vote" do
        # Trigger the behavior that occurs when invalid params are submitted
        SuggestionVote.any_instance.stub(:save).and_return(false)
        post :create, :suggestion_vote => {}
        assigns(:suggestion_vote).should be_a_new(SuggestionVote)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SuggestionVote.any_instance.stub(:save).and_return(false)
        post :create, :suggestion_vote => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested suggestion_vote" do
        # Assuming there are no other suggestion_votes in the database, this
        # specifies that the SuggestionVote created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SuggestionVote.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => @suggestion_vote.id, :suggestion_vote => {'these' => 'params'}
      end

      it "assigns the requested suggestion_vote as @suggestion_vote" do
        put :update, :id => @suggestion_vote.id, :suggestion_vote => @valid_attributes
        assigns(:suggestion_vote).should eq(@suggestion_vote)
      end

      it "redirects to the suggestion_vote" do
        put :update, :id => @suggestion_vote.id, :suggestion_vote => @valid_attributes
        response.should redirect_to(@suggestion_vote)
      end
    end

    describe "with invalid params" do
      it "assigns the suggestion_vote as @suggestion_vote" do
        # Trigger the behavior that occurs when invalid params are submitted
        SuggestionVote.any_instance.stub(:save).and_return(false)
        put :update, :id => @suggestion_vote.id, :suggestion_vote => {}
        assigns(:suggestion_vote).should eq(@suggestion_vote)
      end

      it "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SuggestionVote.any_instance.stub(:save).and_return(false)
        put :update, :id => @suggestion_vote.id, :suggestion_vote => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested suggestion_vote" do
      suggestion_vote = SuggestionVote.create! @valid_attributes
      expect {
        delete :destroy, :id => suggestion_vote.id
      }.to change(SuggestionVote, :count).by(-1)
    end

    it "redirects to the suggestion_votes list" do
      suggestion_vote = SuggestionVote.create! @valid_attributes
      delete :destroy, :id => suggestion_vote.id
      response.should redirect_to(suggestion_votes_url)
    end
  end

end
